version: '3.3'

services:
   frontend:
      container_name: ecomm-frontend
      image: vipul2234/ecomm_frontend:1.0.0
      ports:
         - 80:80
      networks:
         - ecomm-net
      restart: always

   db:
      image: mysql:latest
      restart: always
      command: --default-authentication-plugin=mysql_native_password
      networks:
         - ecomm-net
      environment:
         - MYSQL_DATABASE=e_comm
         # So you don't have to use root, but you can if you like
         - MYSQL_USER=user
         # You can use whatever password you like
         - MYSQL_PASSWORD=password
         # Password for root access
         - MYSQL_ROOT_PASSWORD=password

         - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      ports:
         # <Port exposed> : < MySQL Port running inside container>
         - 3306:3306
      expose:
         # Opens port 3306 on the container
         - 3306
         # Where our data will be persisted
      volumes:
         - my-db:/var/lib/mysql

   backend:
      container_name: ecomm-backend
      image: vipul2234/ecomm_backend:1.0.0
      restart: always
      networks:
         - ecomm-net
      ports:
         - 3001:3001
      depends_on: 
         - db

networks:
     ecomm-net:
# Names our volume
volumes:
  my-db:
